name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s . -p "unitest.py"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull casschang02/flask-sugarcane-app:latest  # Correct image name and tag

      - name: Run tests inside Docker container
        run: |
          docker run --rm casschang02/flask-sugarcane-app:latest pytest # Adjust test command accordingly
            
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_PUBLIC_DNS }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_KEY }}
          port: 22
          script: |
                    docker pull casschang02/flask-sugarcane-app:latest
                    docker rm -f flask-app || true
                    docker run -d --name flask-app -p 8080:8080 casschang02/flask-sugarcane-app:latest
