name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s . -p "unit_test.py"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull flask-sugarcane-app:latest

      - name: Run tests inside Docker container
        run: |
          docker run --rm flask-sugarcane-app:latest pytest  # Adjust the test command accordingly

      # If you still want to push the image after tests (optional)
      - name: Push Docker image to DockerHub (optional)
        run: |
          docker tag flask-sugarcane-app:latest ${{ secrets.DOCKER_USERNAME }}/flask-sugarcane-app:latest &&
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-sugarcane-app:latest
